### ISSUE TITLE
The map config directory is not writable by the web server user. You will not be able to edit any files until this is corrected.

### ISSUE THREAD

**Issue by coolvixs** [librenms-plugins/Weathermap#15]
I am getting this error regardless if i chmod 777 configs or chown apache:apache configs.

Thanks in advance.

**Comment by laf** [comment]
Permissions leading upto that directory are probably too strict. Check before configs directory.

**Comment by coolvixs** [comment]
I have tried everything from making the entire librenms directory with 0777 permissions and even changing everything to apache:apache also to librenms:apache.

Still no success. and plus nothing is popping up on audit.log as i have got selinux enabled too.

**Comment by laf** [comment]
Try disabling selinux. Others use this with no issues :/

**Comment by FTBZ** [comment]
Same issue here. I followed the CentOS 7 installation procedure using a librenms user member of the Apache group. I've tried to add 777 and disable SELinux and this is the same problem. An idea more?

**Comment by darkfritz2** [comment]
i have the same problem: CentOS 7, librenms user member and i added both: hown apache:apache configs/ AND chmod 777 configs and still doesn't work. it's about the folder in /opt/librenms/html/plugins/Weathermap/configs right?
