### ISSUE TITLE
Navigation Bar Menu

### ISSUE THREAD

**Issue by elleryweber** [librenms-plugins/Weathermap#16]
I'm a subscriber of the Observium platform, and am looking at moving over to LibreNMS. One thing I like is that the Weathermap plugin for Observium has an entry in the navbar along the top. I've installed the weathermap plugin in my LibreNMS instance, but was wondering if there was something similar to allow quick access to my maps.

**Comment by laf** [comment]
Hi,

This is a question for the LibreNMS developers. Please post the issue in GitHub.com/librenms/librenms
