### ISSUE TITLE
New Installs are failing

### ISSUE THREAD

**Issue by scottscreations** [librenms-plugins/Weathermap#23]
I have been installing fresh instances for clients with the latest weathermap on this repo and a fresh install of librenms. I follow the instructions https://github.com/librenms-plugins/Weathermap/blob/master/INSTALL.md

everything seems great until I started adding a node and Pick from LibreNMS.

Here is the log dump from my error logs. Librenms owns the files and i am not sure whats going on.

`[Tue Feb 23 12:24:48.047924 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Notice:  Undefined index: install_dir in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 44, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048180 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(/includes/defaults.inc.php): failed to open stream: No such file or directory in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 45, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048309 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(): Failed opening '/includes/defaults.inc.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 45, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048485 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  chdir(): No such file or directory (errno 2) in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 49, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048648 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(/includes/definitions.inc.php): failed to open stream: No such file or directory in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 51, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048677 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(): Failed opening '/includes/definitions.inc.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 51, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048721 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(/includes/functions.php): failed to open stream: No such file or directory in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 52, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048745 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(): Failed opening '/includes/functions.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 52, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048788 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(/html/includes/functions.inc.php): failed to open stream: No such file or directory in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 53, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048812 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  include_once(): Failed opening '/html/includes/functions.inc.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 53, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048886 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Warning:  require_once(/html/includes/authenticate.inc.php): failed to open stream: No such file or directory in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 54, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=
[Tue Feb 23 12:24:48.048911 2016] [:error] [pid 8704] [client 10.20.11.39:60134] PHP Fatal error:  require_once(): Failed opening required '/html/includes/authenticate.inc.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenms/html/plugins/Weathermap/data-pick.php on line 54, referer: http://192.168.1.20/plugins/Weathermap/editor.php?mapname=District-Office.conf&plug=`

**Comment by scottscreations** [comment]
Doh, figured it out the install_dir needed to be uncommented out even though I had it in /opt/librenms.

**Comment by laf** [comment]
:)

**Comment by pitoganzado** [comment]
Sorry to open again this issue, how can i "uncommented" the install_dir?
Thanks!

**Comment by laf** [comment]
Probably $config['install_dir'] in config.php for your librenms install

**Comment by pitoganzado** [comment]
perfect **Iaf**, thats it!
change this:
**_### Locations - it is recommended to keep the default
#$config['install_dir']  = "/opt/librenms";_**
to:

**_### Locations - it is recommended to keep the default
$config['install_dir']  = "/opt/librenms";_**

and is working now :)
thanks again!
