### ISSUE TITLE
Edit config is available for non admin librenms user

### ISSUE THREAD

**Issue by mkratz** [librenms-plugins/Weathermap#24]
I noticed today that when logged in as a non-admin user in librenms, the edit config HREF is available on the weathermap landing page. It appears to be fully functional and I can load the map editor as an unprivileged user.

**Comment by laf** [comment]
This isn't a librenms thing. The editor is standalone so we can't protect it.

**Comment by mkratz** [comment]
Thanks @laf wasn't aware of that.
