### ISSUE TITLE
Q: How to display maps inside LibreNMS?

### ISSUE THREAD

**Issue by huegelc** [librenms-plugins/Weathermap#35]
Hi,

I´ve setup weathermap and so far the maps are created. But how can I display the maps inside librenms-gui? Right now I have to access the maps like: https://<ip-librenms>/plugins/Weathermap/map.html?
Also the hover images doesn´t display. Thank you for your support.

**Comment by laf** [comment]
You can't. If you want that then you're best posting an issue on librenms github
