### ISSUE TITLE
Plugin Fails Looking for includes/init.php

### ISSUE THREAD

**Issue by boardbd** [librenms-plugins/Weathermap#38]
After installing and activating plugin, clicking on the link for the editor results in a broken page and the following in /opt/librenms/error_log

PHP Fatal error:  require(): Failed opening required '/opt/librenms/includes/init.php' (include_path='.:/usr/share/php') in /opt/librenms/html/plugins/Weathermap/editor.php on line 50

The init.php file does not exist in the librenms install.

**Comment by sahilganguly** [comment]
Same.

**Comment by laf** [comment]
Your librenms install needs to be up to date.
