### ISSUE TITLE
Where is link to weathermap in librenms menu?

### ISSUE THREAD

**Issue by janix** [librenms-plugins/Weathermap#42]
Good morning.
I installed weathermap plugin into librenms. Then I activated this plugin, and I can created map.
But I can't see anywhere my created weathermaps? Should I do edit or turn on something?
Or maybe copying / install missing dependencies?

Where should be link to weathermap in libreNMS menu?
Thank you in advance for your response. 

Best regards,
Janusz Janik

**Comment by laf** [comment]
Their is no links, you just go to the html page that has been generated directly.

**Comment by janix** [comment]
Ok, 
do you know whether is planned display maps in LibreNMS interface?
I mean functionality similar like cacti - showing maps is embedded into the system.
