### ISSUE TITLE
HTML Pages not being created

### ISSUE THREAD

**Issue by spilegi** [librenms-plugins/Weathermap#44]
I've done a fresh install of LibreNMS, and cloned from github.  Even setting the permissions for the entire WeatherMap directory to 777 did not output any html pages.

Am I mssing something.  I can get to the editor, and my .conf file are saving.  Am I missing something?  how would I then see the Weathermap?

**Comment by spilegi** [comment]
If I run the cli command i receive the below error, but some of the weathermap is generated
![image](https://cloud.githubusercontent.com/assets/2237483/22166728/8113d5b6-df30-11e6-9168-fab11495f7a4.png)

**Comment by laf** [comment]
Have you followed the instructions and set the cron up?
