### ISSUE TITLE
HTTP ERROR 500 / Weathermap Editor

### ISSUE THREAD

**Issue by tracerrx** [librenms-plugins/Weathermap#45]
When clicking "Edit" receive HTTP 500

**VALIDATE**
==========================================================
Component | Version
--------- | -------
LibreNMS  | d67d62eacb880163768588fb0c1b879cbcfa77d5
DB Schema | 187
PHP       | 7.0.18
MySQL     | 5.5.52-MariaDB
RRDTool   | 1.4.8
SNMP      | NET-SNMP 5.7.2
==========================================================

**Error Log**
`2017/04/27 23:03:33 [error] 12180#0: *1377 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dbDelete() in /opt/librenms/html/includes/authenticate.inc.php:24
Stack trace:
#0 /opt/librenms/html/plugins/Weathermap/editor.php(54): require_once()
#1 {main}
  thrown in /opt/librenms/html/includes/authenticate.inc.php on line 24" while reading response header from upstream, client:`

**Comment by laf** [comment]
Is your weathermap plugin up to date? Seems to work ok for me.

**Comment by tracerrx** [comment]
git update did the trick...
