### ISSUE TITLE
PHP Fatal Error - failed opening required '/opt/librenms/includes/init.php'

### ISSUE THREAD

**Issue by tuksaur** [librenms-plugins/Weathermap#46]
PHP Fatal error:  require(): Failed opening required '/opt/librenms/includes/init.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/librenms/html/plugins/Weathermap/editor.php on line 50, referer: http://[librenmsIP]/plugin/p=Weathermap

fresh install, no "init.php" file anywhere on box... do i need to manually create this file or should it be included w/ the installation of Weathermap?

**Comment by laf** [comment]
Update your librenms install
