### ISSUE TITLE
How to Diaplay Ping Latency in Weatheramp

### ISSUE THREAD

**Issue by Majesticops** [librenms-plugins/Weathermap#47]
Hi

I would like to display ping latency in my maps as shown below. Can someone assist I  pointing out I could do this.

Thanks

![weathermap2](https://user-images.githubusercontent.com/33343123/33523422-9835698e-d80f-11e7-9e90-3f8a38d9f9f0.jpg)

**Comment by Majesticops** [comment]
The above was done from cacti I would like to know how do it with Librenms

**Comment by Majesticops** [comment]
Any one have an idea to do this?

**Comment by laf** [comment]
Please be patient, no one is here to provide 24/7 support.

This is a weathermap question. You need to find out how you get that data in weathermap first. Once you know that, you can ask again about how you get that data out of Lnms.

**Comment by Majesticops** [comment]
Okay cool thank you. I have a starting point.

**Comment by Majesticops** [comment]
Hi 

Below is the config im using in a node, Im using the weathermap plugin for Librenms. I have been able to get the OVERLIBGRAPH working I just need to know what TARGET syntax i must use to retrieve the current CPU utilization out of the librenms RRD files. Current the TAGET syntax below is NOT working.

NODE 39
	LABEL {node:this:outpercent:%k}%
	OVERLIBGRAPH http://10.1.35.60/graph.php?id=114&type=processor_usage&height=100&width=512
	TARGET gauge:./10.1.254.250/processor-cpm-1.rrd:usage:AVERAGE
	POSITION 164 228

**Comment by laf** [comment]
Maybe:
`TARGET:./10.1.254.250/processor-cpm-1.rrd:usage:usage`

**Comment by Majesticops** [comment]
Great stuff let me give that a try will let you know.

**Comment by Majesticops** [comment]
Looks like it working the problem now is it says my CPU is 342 % 

![image](https://user-images.githubusercontent.com/33343123/33817471-71c5a50e-de48-11e7-8beb-03bef9dac3ca.png)

**Comment by Majesticops** [comment]
Hi Laf 

I got it working by doing the following:

NODE node00722
	LABEL {node:this:outpercent:%k}%
	OVERLIBGRAPH http://10.1.35.60/graph.php?id=114&type=processor_usage&height=100&width=512
	TARGET gauge:./10.1.254.250/processor-cpm-1.rrd:usage:usage
	POSITION 164 228

![image](https://user-images.githubusercontent.com/33343123/33821216-b9a82e6a-de5b-11e7-8727-5d0df58c3b7e.png)

This can be closed.

I will see if I can get the ping latency on the wearthermap

**Comment by Majesticops** [comment]
I got icmp latency working:

NODE node02686
	LABEL {node:this:bandwidth_in:%d} ms
	OVERLIBGRAPH http://10.1.35.60/graph.php?type=device_ping_perf&device=15&height=100&width=512
	TARGET gauge:./10.1.255.251/ping-perf.rrd:ping:-
	POSITION 92 690

**Comment by olandou** [comment]
Dear Majesticops,

I really appreciate your topic on this.
could you have the same template for :
- Device memory
- paket loss
- optical power

Thanks for your support.
