### ISSUE TITLE
no map generation in docker environment

### ISSUE THREAD

**Issue by sk4mi** [librenms-plugins/Weathermap#57]
Hi,
first issue submit here [https://github.com/librenms/docker/issues/16](url)

I’m trying to install weathermap on the official docker image crafted by @crazy-max.
I followed docs on a fresh install, it works.
But when trying in docker, the editor works but it can’t generate maps in output folder.

Thanks for all your work.
Sk4mi.

**Comment by laf** [comment]
I'm closing this down, all of your issues are really upstream of this plugin, they may be resolved already but no work is going in to this plugin until network weathermap finishes the work off to split it's code base out.

Pull requests accepted though.
