### ISSUE TITLE
executing map-poller.php from UI

### ISSUE THREAD

**Issue by krakazyabra** [librenms-plugins/Weathermap#58]
Hi!  
I want to make custom link to file `map-poller.php` (to refresh map every time I want, not even from cron).  
So, i added this link, but during execution, I get error  

```#!/usr/bin/env php ERROR: map-poller.php should ONLY be run as a CGI script!```  
  
I'm using nginx with php-fpm. How can i execute this file from interface?

**Comment by sk4mi** [comment]
As the error says: you can’t execute it outside cli. 
If you really want, you can modify the script and remove if statement. But it’s not recommended.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krakazyabra** [comment]
I walkedthroug this error:   
NGINX+FastCGI+perl script  
```#!/usr/bin/perl
print "Content-type: text/html\n\n";
system("sudo -u librenms /opt/librenms/html/plugins/Weathermap/map-poller.php");
```  
And everything is working fine.

**Comment by laf** [comment]
This isn't a plugin issue but is from the network weathermap software so closing this down.
