### ISSUE TITLE
Plugin should display maps

### ISSUE THREAD

**Issue by supertylerc** [librenms-plugins/Weathermap#7]
This plugin should display the maps it generates on the plugin page (or provide navigation to reach the maps).

**Comment by supertylerc** [comment]
I have a PR for this, but it's on a Linux box because #8 is wreaking havoc on my ability to test locally.  I'll have to setup the Linux box later to be able to push its changes.

**Comment by laf** [comment]
Is it done by listing files in a directory? It's possible for users to output the html files to anywhere but I could update the docs to say, if you put them in X it will be in the Webui.

**Comment by supertylerc** [comment]
It looks in the `output/` directory and loops through to create an `<li>` tag for each file ending in `*.png`.

**Comment by supertylerc** [comment]
Example of the HTML output (cleaned up for legibility):

```html
<div class="row">
  <div class="col-md-12">
    Click <a href="plugins/Weathermap/editor.php">here to access the editor</a> where you can create and manage maps.
    <div class="container">
      <ul class="list-inline">
        <li>
          <img class="img-responsive" src="plugins/Weathermap/output/core.png"/>
        </li>
        <li>
          <img class="img-responsive" src="plugins/Weathermap/output/routers.png"/>
        </li>
      </ul>
    </div>
  </div>
</div>
```

**Comment by supertylerc** [comment]
And an example in mobile proportions.

![screen shot 2015-04-07 at 2 53 21 pm](https://cloud.githubusercontent.com/assets/4076147/7034382/e5c57040-dd35-11e4-80f7-42534d86313e.png)

**Comment by laf** [comment]
Looks good :)

**Comment by supertylerc** [comment]
See PR #9 for the implementation of the feature.

**Comment by supertylerc** [comment]
Ultimately, I think that steps should be taken to generate the overlib HTML for the plugin page.  This is probably a good first step to something useful, though.

**Comment by supertylerc** [comment]
I just added a new commit to #9 that will turns the image into a link to the overlib.  Definitely not the greatest UX, but hopefully better than fumbling around for the correct paths.

**Comment by laf** [comment]
Thanks @supertylerc :) 

Just merged it in now.

**Comment by supertylerc** [comment]
Awesome.  Thanks for merging.  :)
