### ISSUE TITLE
name.jpg and name.html not getting created

### ISSUE THREAD

**Issue by tdhendup** [librenms-plugins/Weathermap#94]
Hi All,
I was trying to integrate weathermap with librenms. The integration works but when I try to create the map from the librenms admin page, I don't see the following files created
map_name.jpg and map_name.html 
1. Checked under Weathermap-NO
2. Check under weathermap/output-NO
However, the map_name.conf gets created under Weathermap/configs directory. Please advice.

**Comment by vivitare** [comment]
Hello, I've got the same issue. I don't understand because the last PR - [Weathermap fix for local rrdcached users and cron fix](https://github.com/librenms-plugins/Weathermap/pull/85) should fix this issue, but she's not.

If someone have an idea

**Comment by vivitare** [comment]
Hi @tdhendup , did you try with Docker deployment ? Because for me it's not working even if php-pear is installed.

**Comment by tdhendup** [comment]
Hi - No I didn’t use docker . I installed on the bare metal server .
